common: &common
  adapter: postgresql
  username: fabio
  password:  # from psql setup, see Postgresql

development:
  <<: *common
  database: locamotiva2_development

test:
  <<: *common
  database: locamotiva2_test

production:
  <<: *common
  database: locamotiva2_production