development:
  adapter: mysql2
  encoding: utf8
  database: locamotiva_dev
  pool: 5
  username: root
  password:

test: 
  adapter: mysql2
  encoding: utf8
  database: locamotiva_test
  pool: 5
  username: root
  password:

production:
  development
